// tslint:disable: max-line-length


export const PATCH_TABLE = [
    {num: 0 , descrip: '“#1 Worker”'},
    {num: 1 , descrip: 'Security Guard patch'},
    {num: 2 , descrip: 'Blood Type (Reference Patch)'},
    {num: 3 , descrip: 'Red Shirt Logo'},
    {num: 4 , descrip: '“Don’t Run You’ll Only Die Tired” Backpatch'},
    {num: 5 , descrip: 'Poker Hand: Dead Mans Hand (Aces full of 8s)'},
    {num: 6 , descrip: 'Biohazard Symbol'},
    {num: 7 , descrip: 'Mr. Yuck'},
    {num: 8 , descrip: 'Nuclear Symbol'},
    {num: 9 , descrip: '“Eat The Rich”'},
    {num: 10, descrip: ' “Be Sure: Doubletap”'},
    {num: 11, descrip: ' Flame Emoji'},
    {num: 12, descrip: ' Smiley Face (Glow in the Dark)'},
    {num: 13, descrip: ' “Smile: Big Brother is Watching”'},
    {num: 14, descrip: ' Jolly Roger'},
    {num: 15, descrip: ' Viking Skull'},
    {num: 16, descrip: ' “APEX PREDATOR” (Sabertooth Skull)'},
    {num: 17, descrip: ' Pin-Up (Ace of Spades)'},
    {num: 18, descrip: ' Queen of Hearts'},
    {num: 19, descrip: ' Pin-Up (Mechanic)'},
    {num: 20, descrip: ' BOHICA (Bend Over Here It Comes)'},
    {num: 21, descrip: ' Front Towards Enemy (Claymore Mine)'},
    {num: 22, descrip: ' Pin-Up (Riding Missile)'},
    {num: 23, descrip: ' FUBAR'},
    {num: 24, descrip: ' “I’m A (Love) Machine”'},
    {num: 25, descrip: ' Medic Patch (Skull and Crossbones on Logo)'},
    {num: 26, descrip: ' HELLO MY NAME IS:'},
    {num: 27, descrip: ' “Powered By Coffee”'},
    {num: 28, descrip: ' “Take Me To Your Leader” (UFO)'},
    {num: 29, descrip: ' “DO YOUR JOB”'},
    {num: 30, descrip: ' “Take My Life (Please)”'},
    {num: 31, descrip: ' “All Out of Fucks To Give” (Astronaut with Turned Out Pockets)'},
    {num: 32, descrip: ' Allergic To Bullshit (Medical Style Patch)'},
    {num: 33,  descrip: '“Fix Me First” (Caduceus)'},
    {num: 34,  descrip: '“Upstanding Citizen”'},
    {num: 35,  descrip: 'NASA Logo'},
    {num: 36,  descrip: '“Cowboy Up” (Crossed Revolvers)'},
    {num: 37,  descrip: 'Dove in Crosshairs'},
    {num: 38,  descrip: 'Chibi Cthulhu'},
    {num: 39,  descrip: '“Welcome to the DANGER ZONE”'},
    {num: 40,  descrip: 'Skull and Crossed Wrenches'},
    {num: 41,  descrip: 'Pin-Up (Succubus)'},
    {num: 42,  descrip: '“DILLIGAF?”'},
    {num: 43,  descrip: '“DRINK / FIGHT / FUCK”'},
    {num: 44,  descrip: '“Work Hard / Party Harder”'},
    {num: 45,  descrip: 'Mudflap Girl'},
    {num: 46,  descrip: 'Fun Meter (reading: bad time)'},
    {num: 47,  descrip: '“GAME OVER” (Bride & Groom)'},
    {num: 48,  descrip: 'Heart'},
    {num: 49,  descrip: '“IMPROVE / ADAPT / OVERCOME”'},
    {num: 50,  descrip: '“SUCK IT UP”'},
    {num: 51,  descrip: 'HMFIC (Head Mother Fucker In Charge)'},
    {num: 52,  descrip: '“Troubleshooter”'},
    {num: 53,  descrip: '“IF I’M RUNNING KEEP UP” Backpatch'},
    {num: 54,  descrip: 'Crossed Hammers with Wings'},
    {num: 55,  descrip: '“Keep Well Lubricated”'},
    {num: 56,  descrip: 'Soviet Hammer & Sickle'},
    {num: 57,  descrip: '“Plays Well With Others”'},
    {num: 58,  descrip: '“Live Free and Die”'},
    {num: 59,  descrip: 'Pin-Up (Nurse): “The Louder You Scream the Faster I Come”'},
    {num: 60,  descrip: '“Meat Bag”'},
    {num: 61,  descrip: '“I Am Not A Robot”'},
    {num: 62,  descrip: 'Red Gear'},
    {num: 63,  descrip: '“I Can’t Fix Stupid”'},
    {num: 64,  descrip: '“Space IS My Home” (Sad Astronaut)'},
    {num: 65,  descrip: 'All Seeing Eye'},
    {num: 66,  descrip: '“Do I LOOK Like An Expert”'},
    {num: 67, descrip: '“NOMAD”'},
    {num: 68, descrip: '“I’m Not A Rocket Scientist / But You’re An Idiot”'},
    {num: 69, descrip: '“LONER”'},
    {num: 70, descrip: '“I Am My Brothers Keeper”'},
    {num: 71, descrip: '“Mama Tried”'},
    {num: 72, descrip: 'Black Widow Spider'},
    {num: 73, descrip: '“My Other Ride Married You”'},
    {num: 74, descrip: '“One Size Fits All” (Grenade)'},
    {num: 75, descrip: 'Grim Reaper Backpatch'},
    {num: 76, descrip: 'трахаться (Get Fucked, Russian)'},
    {num: 77, descrip: '“Smooth Operator”'},
    {num: 78, descrip: 'Atom Symbol'},
    {num: 79, descrip: '“For Science!”'},
    {num: 80, descrip: '“Actually, I Am A Rocket Scientist”'},
    {num: 81, descrip: '“Help Wanted”'},
    {num: 82, descrip: 'Princess'},
    {num: 83, descrip: '“I Like My Tools Clean / And My Lovers Dirty”'},
    {num: 84, descrip: '“GOOD BOY”'},
    {num: 85, descrip: 'Dice (Snake Eyes)'},
    {num: 86, descrip: '“Travel To Distant Exotic Places / Meet Unusual Things / Get Eaten”'},
    {num: 87, descrip: '“Good” (Brain)'},
    {num: 88, descrip: '“Bad Bitch”'},
    {num: 89, descrip: '“Too Pretty To Die”'},
    {num: 90, descrip: '“Fuck Forever” (Roses)'},
    {num: 91, descrip: 'Icarus'},
    {num: 92, descrip: '”Girls Best Friend” (Diamond)'},
    {num: 93, descrip: 'Risk of Electrocution Symbol'},
    {num: 94, descrip: 'Inverted Cross'},
    {num: 95, descrip: '“Do You Sign My Paychecks?” Backpatch'},
    {num: 96, descrip: '“I ♥ Myself”'},
    {num: 97, descrip: 'Double Cherry'},
    {num: 98, descrip: '“Volunteer”'},
    {num: 99, descrip: '“Solve Et Coagula” (Baphomet)'},
  ];
export const TRINKET_TABLE = [
    { num: 0, descrip: 'Preserved Insectile Aberration'},
    { num: 1, descrip: 'Faded Green Poker Chip'},
    { num: 2, descrip: 'Antique Company Script (Asteroid Mine)'},
    { num: 3, descrip: 'Dessicated Husk Doll'},
    { num: 4, descrip: 'Alien Pressed Flower (common)'},
    { num: 5, descrip: 'Necklace of Shell Casings'},
    { num: 6, descrip: 'Corroded Android Logic Core'},
    { num: 7, descrip: 'Pamphlet: Signs of Parasitical Infection'},
    { num: 8, descrip: 'Manual: Treat Your Rifle Like A Lady'},
    { num: 9, descrip: 'Bone Knife'},
    { num: 10, descrip: 'Calendar: Alien Pin-Up Art'},
    { num: 11, descrip: 'Dog Tags (Heirloom)'},
    { num: 12, descrip: 'Holographic Serpentine Dancer'},
    { num: 13, descrip: 'Snake Whiskey'},
    { num: 14, descrip: 'Medical Container, Purple Powder'},
    { num: 15, descrip: 'Pills: Male Enhancement, Shoddy'},
    { num: 16, descrip: 'Casino Playing Cards'},
    { num: 17, descrip: 'Lagomorph Foot'},
    { num: 18, descrip: 'Moonstone Ring'},
    { num: 19, descrip: 'Manual: Mining Safety and You'},
    { num: 20, descrip: 'Pamphlet: Against Human Simulacrum'},
    { num: 21, descrip: 'Animal Skull, 3 Eyes, Curled Horns'},
    { num: 22, descrip: 'Bartender’s Certification (Expired)'},
    { num: 23, descrip: 'Bent Wrench'},
    { num: 24, descrip: 'Prospecting Mug, Dented'},
    { num: 25, descrip: 'Eerie Mask'},
    { num: 26, descrip: 'Vantablack Marble'},
    { num: 27, descrip: 'Ivory Dice'},
    { num: 28, descrip: 'Tarot Cards, Worn, Pyrite Gilded edges'},
    { num: 29, descrip: 'Bag of Assorted Teeth'},
    { num: 30, descrip: 'Ashes (A Relative)'},
    { num: 31, descrip: 'DNR Beacon Necklace'},
    { num: 32, descrip: 'Cigarettes (Grinning Skull)'},
    { num: 33, descrip: 'Pills: Areca Nut'},
    { num: 34, descrip: 'Rejected Application (Colony Ship)'},
    { num: 35, descrip: 'Pamphlet: Android Overlords'},
    { num: 36, descrip: 'Smut (Seditious): The Captain, Ordered'},
    { num: 37, descrip: 'Key (Childhood Home)'},
    { num: 38, descrip: 'Manual: Panic: Harbinger of Catastrophe'},
    { num: 39, descrip: 'Token: “Is Your Morale Improving?”'},
    { num: 40, descrip: 'Phosphorescent Sticks, Neon'},
    { num: 41, descrip: 'Pamphlet: The Indifferent Stars'},
    { num: 42, descrip: 'Calendar: Military Battles'},
    { num: 43, descrip: 'Manual: Rich Captain, Poor Captain'},
    { num: 44, descrip: 'Campaign Poster (Home Planet)'},
    { num: 45, descrip: 'Pendant: Shell Fragments Suspended in Plastic'},
    { num: 46, descrip: 'Titanium Toothpick'},
    { num: 47, descrip: 'Gloves, Leather (Xenomorph Hide)'},
    { num: 48, descrip: 'Pamphlet: Zen and the Art of Cargo Arrangement'},
    { num: 49, descrip: 'Pictorial Pornography, Dogeared, Well Thumbed'},
    { num: 50, descrip: 'Brass Knuckles'},
    { num: 51, descrip: 'Fuzzy Handcuffs'},
    { num: 52, descrip: 'Journal of Grudges'},
    { num: 53, descrip: 'Stylized Cigarette Case'},
    { num: 54, descrip: 'Ball of Assorted Gauge Wire'},
    { num: 55, descrip: 'Spanner'},
    { num: 56, descrip: 'Switchblade, Ornamental'},
    { num: 57, descrip: 'Powdered Xenomorph Horn'},
    { num: 58, descrip: 'Bonsai Tree'},
    { num: 59, descrip: 'Golf Club (Putter)'},
    { num: 60, descrip: 'Trilobite Fossil'},
    { num: 61, descrip: 'Pamphlet: A Girl In Every Port'},
    { num: 62, descrip: 'Patched Overalls, Personalized'},
    { num: 63, descrip: 'Fleshy Thing Sealed in a Murky Jar'},
    { num: 64, descrip: 'Spiked Bracelet'},
    { num: 65, descrip: 'Harmonica'},
    { num: 66, descrip: 'Manual: Spacefarer\'s Almanac'},
    { num: 67, descrip: 'Faded Photograph, A Windswept Heath'},
    { num: 68, descrip: 'Stress Ball reads: Zero Stress in Zero G'},
    { num: 69, descrip: 'Manual: Moonshining With Gun Oil & Fuel'},
    { num: 70, descrip: 'Gyroscope, Bent, Tin'},
    { num: 71, descrip: 'Coffee Cup, Chipped, HAPPINESS IS MANDATORY'},
    { num: 72, descrip: 'Darts, Magnetic'},
    { num: 73, descrip: 'Spray Paint'},
    { num: 74, descrip: 'Wanted Poster, Weathered'},
    { num: 75, descrip: 'Locket, Hair Braid'},
    { num: 76, descrip: 'Pick, Miniature'},
    { num: 77, descrip: 'Blanket, Fire Retardant'},
    { num: 78, descrip: 'Hooded Parka, Fleece-Lined'},
    { num: 79, descrip: 'BB Gun'},
    { num: 80, descrip: 'Flint Hatchet'},
    { num: 81, descrip: 'Pendant: Two Astronauts form a Skull'},
    { num: 82, descrip: 'Rubik\'s Cube'},
    { num: 83, descrip: 'Manual: Survival: Eat Soup With a Knife'},
    { num: 84, descrip: 'Sputnik Pin'},
    { num: 85, descrip: 'Ushanka'},
    { num: 86, descrip: 'Trucker Cap, Mesh, Grey Alien Logo'},
    { num: 87, descrip: 'Menthol Balm'},
    { num: 88, descrip: 'Pith Helmet'},
    { num: 89, descrip: '10x10 Tarp'},
    { num: 90, descrip: 'I Ching, Missing Sticks'},
    { num: 91, descrip: 'Kukri'},
    { num: 92, descrip: 'Trench Shovel'},
    { num: 93, descrip: 'Shiv, Sharpened Butter Knife'},
    { num: 94, descrip: 'Taxidermied Cat'},
    { num: 95, descrip: 'Pamphlet: Interpreting Sheep Dreams'},
    { num: 96, descrip: 'Pair of Shot Glasses, Spent Shotgun Shells'},
    { num: 97, descrip: 'Opera Glasses'},
    { num: 98, descrip: 'Pamphlet: The Relic of Flesh'},
    { num: 99, descrip: 'Miniature Chess Set, Bone, Pieces Missing'},
  ];

export const SPACE_STATION = {
      station_name1: [
        'Azreal\'s',
        'Dunmah\'s',
        'Marut\'s',
        'Gorgon\'s',
        'Soter\'s',
        'Pontian\'s',
        'Vitalin\'s',
        'Iblis\'s',
        'Al-\'Uzza\'s',
        'Vanth\'s'
      ],

      station_name2: [
        'Price',
        'Sorrow',
        'Redemption',
        'Revenge',
        'Ring',
        'Crown',
        'Sword',
        'Shield',
        'Cross',
        'Herald'
      ],

      core_station: [
        'overcrowded habitat colony',
        'palatial estate',
        'secret corporate research facility',
        'marine battle school',
        'bustling trading port',
        'sprawling megatropolis',
        'high security corporate vault',
        'semi-autonomous shipyard',
        'solitary monastary',
        'ancient jump gate'
      ],

      celestial_body: [
        'still terraforming planet',
        'overpopulated slumworld',
        'resource rich planet',
        'desolate planetoid',
        'white dwarf star',
        'moon of an inhabited planet',
        'unpopulated paradise world',
        'giant asteroid cluster',
        'red supergiant',
        'black hole, past event horizon'
      ],

      core_leader: [
        'first-colony descendent',
        'asteroid mining oligarch',
        'reclusive intellectual',
        'scheming marine general',
        'teamster union rep',
        'sadistic decadent',
        'decorated regional governor',
        'rimwar veteran commander',
        'reformed criminal outcast',
        'dynastic child-heir'
      ],

      group: [
        'radical colonial separatists',
        'The Valecore Mining Consortium',
        'The Exo-Credit Federated Union',
        'The 91st Colonial Dragoons',
        'Teamster\'s Local 101977L',
        'The Yamguchi-gumi Clan',
        'The Crashlander Titan 2nd Fleet',
        'The Principality of Christian XII',
        'The Decanon Caliphate',
        'The House of Tarkhan'
      ],

      goods: [
        'equipment',
        'asteroid ore',
        'weapons',
        'scrap metal',
        'prisoners',
        'warp cores',
        'galley stock',
        'ship parts',
        'used ships',
        'fuel'
      ],

      resource: [
        'android laborers',
        'asteroid mining machinery',
        'hardened mercenaries',
        'black market cybermods',
        'life-saving medicine',
        'doctors who don\'t ask questions',
        'rations',
        'out of work scientists',
        'oxygen reserves',
        'recreational drugs'
      ],

      crisis: [
        '<b>Hostage Situation</b>. Command of the station has been taken by a rival faction who demand <u>1d10kcr</u> ransom.',
        '<b>Refugee Crisis</b>. The station is overrun with refugees. Everything is 1d10 + 1x more expensive than usual.',
        '<b>Food Shortage</b>. The station will pay 1d10 + 1kcr for food and another random resource. Theft is rampant.',
        '<b>Quarantine</b>. After boarding the station you learn that it has been quarantined. No one is allowed to leave.',
        '<b>Bout of Civil Unrest</b>. Rioting and looting. Mercenary death squads roam the corridors executing collaborators.',
        '<b>Disaster</b>. Crash landing, mass explosion or sabotage. Station is on full alert and going down without repairs.',
        '<b>General Strike</b>. Unions have organized. Protests, picket lines and intense riots. Commerce is shut down.',
        '<b>Uncanny Abandonment</b>. The station hosts the aftermath of some bloody, haunted or mysterious happening.',
        '<b>Martial Law Edict</b>. All ships are boarded and inspected, station visas are issued and a curfew is in effect.',
        '<b>Blockade</b>. The station is under siege by the rival faction and access has been cut off. Your ship will be boarded.'
      ],

      structure: [
        '<b>Asteroid Surface</b>. This station has been built on the outside surface of the asteroid, much the same way a building rests on the surface of a planet',
        '<b>Asteroid Interior</b>. While there may be structures on the outside of the asteroid the majority of the station exists "underground" as a series of tunnels, caves, or similar structures',
        '<b>Spindle</b>. A common design, shaped like a spinning top with towers rising from the top and/or bottom',
        '<b>Cylinder</b>. The cylinder\'s rotation could provide a rationale for artificial gravity and the station could be quite large, like an O\'Neill Cylinder',
        '<b>Sphere</b>. Can be as big as a Dyson or Bernal Sphere or as small as a single pod-station',
        '<b>Torus/Ring</b>. The most common design. Like the Standford Torus or Bishop Ring, the outer ring could provide enough centrifugal force to provide artifical gravity',
        '<b>Tower</b>. A station with an angular or blocky design, like a skyscraper flung into space',
        '<b>Modular</b>. Built from discrete modules or "beads" that can be removed or added on to',
        '<b>Platform</b>. Design based on a large ship with clearly defined levels/decks',
        '<b>Amalgamation</b>.'
      ],

      common_problems: [
        '<b>No Artificial Gravity</b>. Zero-G Skill Check for complex maneuvers',
        '<b>Resource Scarcity</b>. Food, water, oxygen, shelter is hard to find',
        '<b>Trade Good Scarcity</b>. Lack of fuel, warp cores, ammunition',
        '<b>Oxygen Poor</b>. Strenuous activities at [-]. O2 taxation',
        '<b>Non-standard Day/Night Cycle</b>. Resting at [-]',
        '<b>Poor Water Treatment Facilities</b>. Healing at [-]',
        '<b>Low Security</b>. High risk of theft, threat of violence, piracy, etc',
        '<b>High Secuirty</b>. High risk of authoritarian police, taxation, prison, etc.',
        '<b>Xenophobic Population</b>. Suspicious/hostile to stranger/outsiders',
        '<b>Poor Maintenance</b>. Minimum Stress +1. Resting and Healing at [-]. High risk of damage to the station during combat',
      ],

      noteworthy_locations: [
        ...Array(3).fill('repair'),
        'port',
        'colony',
        'military',
        'mining',
        'corporate',
        'prison',
        'religious'
      ],

        repair: [
          ...Array(5).fill('dry dock'),
          ...Array(5).fill('vehicle repair'),
          ...Array(5).fill('chop shop'),
          ...Array(5).fill('bars'),
          ...Array(5).fill('showers'),
          ...Array(5).fill('capsule motel'),
          ...Array(5).fill('navigation library'),
          ...Array(5).fill('warp core storage'),
          ...Array(5).fill('teamster union hall'),
          ...Array(5).fill('military lounge'),
          ...Array(5).fill('commercial travel'),
          ...Array(5).fill('private hanger'),
          ...Array(5).fill('showers'),
          ...Array(5).fill('metal foundry'),
          ...Array(5).fill('Ore Trade/Refinery'),
          ...Array(5).fill('food court'),
          ...Array(5).fill('Fuel Bay/Warp Cores'),
          ...Array(5).fill('slickscreens'),
          'red light district',
          'black market',
          'tiny chapel',
          'weapons fabrication',
          'advanced r&d',
          'experimental ftl lab',
          'astronavigator terminals',
          'station overseer',
          'holding cells',
          'power station'
        ],

        port: [
          ...Array(5).fill('food stand'),
          ...Array(5).fill('dry dock'),
          ...Array(5).fill('fence for stolen goods'),
          ...Array(5).fill('black market'),
          ...Array(5).fill('re-sleeving facility'),
          ...Array(5).fill('cybermod shop'),
          ...Array(5).fill('imports warehouse'),
          ...Array(5).fill('designer drugs'),
          ...Array(5).fill('gene therapy'),
          ...Array(5).fill('holotat shop'),
          ...Array(5).fill('glass blower'),
          ...Array(5).fill('technobladesmith'),
          ...Array(5).fill('slaughter yard'),
          ...Array(5).fill('fabric loom'),
          ...Array(5).fill('sweatshop'),
          ...Array(5).fill('gambling house'),
          ...Array(5).fill('dance club'),
          ...Array(5).fill('teamster bar'),
          'cassette library',
          'specimens & oddities',
          'red light district',
          'military black site',
          'navigator guildhouse',
          'decorative rugs',
          'tea shop',
          'old earth antique shop',
          'custom androids',
          'ship designer'
        ],

        colony: [
          ...Array(5).fill('Farming Unit              '),
          ...Array(5).fill('Food Court                '),
          ...Array(5).fill('Slickscreen               '),
          ...Array(5).fill('Bar/Club                  '),
          ...Array(5).fill('Slaughterhouse            '),
          ...Array(5).fill('Seed/Gene Storage         '),
          ...Array(5).fill('Sleeping Units            '),
          ...Array(5).fill('Meeting                   '),
          ...Array(5).fill('Aquaponics Tanks          '),
          ...Array(5).fill('Markets                   '),
          ...Array(5).fill('School/Training Facilities'),
          ...Array(5).fill('Library/Research Lab      '),
          ...Array(5).fill('Upscale Housing           '),
          ...Array(5).fill('Security Outpost          '),
          ...Array(5).fill('Clinic                    '),
          ...Array(5).fill('Factory                   '),
          ...Array(5).fill('Greenhouse                '),
          ...Array(5).fill('Turret Emplacement        '),
          'Red Light District        ',
          'Brig                      ',
          'Power Station             ',
          'Pharmalab                 ',
          'Governor’s Mansion        ',
          'Armory                    ',
          'Temple                    ',
          'Courthouse/Records        ',
          'Landing Strip             ',
          'Communication Array       ',
        ],

        military: [
          ...Array(5).fill('Admin Offices'),
          ...Array(5).fill('Drop Station'),
          ...Array(5).fill('Training Rooms'),
          ...Array(5).fill('Shooting Range'),
          ...Array(5).fill('Command Center'),
          ...Array(5).fill('Defensive Weaponry'),
          ...Array(5).fill('Vehicle Repair Center'),
          ...Array(5).fill('Square Brig'),
          ...Array(5).fill('Troopship Carrier'),
          ...Array(5).fill('Barracks'),
          ...Array(5).fill('Interrogation Rooms'),
          ...Array(5).fill('Medbay'),
          ...Array(5).fill('R&D Department'),
          ...Array(5).fill('Drop-tank Hangar'),
          ...Array(5).fill('Mess Hall'),
          ...Array(5).fill('Officer’s Lounge'),
          ...Array(5).fill('“Off-base” Housing'),
          ...Array(5).fill('Master Computer'),
          'Diplomatic Embassy',
          'Officer’s Quarters',
          'Weapon Testing',
          'Fighter Squadron',
          'Ammunition Storage',
          'Re-Sleeving Facility',
          'Cryochambers',
          'Intelligence Facility',
          'Exomech Hangar',
          'Massive Weapon',
        ],

        mining: [
          ...Array(5).fill('Material Processing    '),
          ...Array(5).fill('Shipping Warehouse     '),
          ...Array(5).fill('Storage Warehouse      '),
          ...Array(5).fill('Dry Dock               '),
          ...Array(5).fill('Assembly Line          '),
          ...Array(5).fill('Metal Refinery         '),
          ...Array(5).fill('Air Scrubber           '),
          ...Array(5).fill('Water Reclamation      '),
          ...Array(5).fill('Sleeping Pods          '),
          ...Array(5).fill('Cafeteria              '),
          ...Array(5).fill('Showers/Soakers        '),
          ...Array(5).fill('Corp. Conference Room  '),
          ...Array(5).fill('Garage/Hangar          '),
          ...Array(5).fill('Geology Lab            '),
          ...Array(5).fill('Records/Maps/Blueprints'),
          ...Array(5).fill('Slickscreen            '),
          ...Array(5).fill('Fighting Ring          '),
          ...Array(5).fill('Android Maintenance    '),
          'Conjugal Trailers      ',
          'Xenobio Lab            ',
          'Extraction Point       ',
          'Infraction Cells       ',
          'Cloning Facility       ',
          'Communications         ',
          'Exosuit Hangar/Repair  ',
          'Life Support           ',
          'Laser Drilling Array   ',
          'Company Store          ',
        ],

        corporate: [
          ...Array(5).fill('Offices                 '),
          ...Array(5).fill('Open Floor Plan Office  '),
          ...Array(5).fill('Cubicles                '),
          ...Array(5).fill('Testing Lab             '),
          ...Array(5).fill('AI Computer Banks       '),
          ...Array(5).fill('Labratory               '),
          ...Array(5).fill('Quarantine Room         '),
          ...Array(5).fill('Data Analysis Office    '),
          ...Array(5).fill('Android Storage         '),
          ...Array(5).fill('Warehouse               '),
          ...Array(5).fill('Shipping & Receiving    '),
          ...Array(5).fill('Mail Rooms              '),
          ...Array(5).fill('Meeting Rooms           '),
          ...Array(5).fill('Clean Room              '),
          ...Array(5).fill('Employee Housing        '),
          ...Array(5).fill('Hazardous Materials     '),
          ...Array(5).fill('Cryostorage             '),
          ...Array(5).fill('Containment Lab         '),
          'Private Offices         ',
          'Luxurious Boardroom     ',
          'High Security Vault     ',
          'Illegal DNA Splicing Lab',
          'Embryonic Storage       ',
          'Morgue                  ',
          'Animal Testing Pens     ',
          'Killteam Barracks       ',
          'Experiment #237         ',
          'Mega-AI Brain           ',
        ],

        prison: [
          ...Array(5).fill('Ruined Cellblock      '),
          ...Array(5).fill('Administration Offices'),
          ...Array(5).fill('Morgue                '),
          ...Array(5).fill('Riot Armory           '),
          ...Array(5).fill('Guard Quarters        '),
          ...Array(5).fill('High Security Area    '),
          ...Array(5).fill('Isolation Chambers    '),
          ...Array(5).fill('Cryostorage'),
          ...Array(5).fill('VR Exercise Yard      '),
          ...Array(5).fill('Prison Cells          '),
          ...Array(5).fill('Group Dormitory       '),
          ...Array(5).fill('Quarantine Unit       '),
          ...Array(5).fill('Solitary Confinement  '),
          ...Array(5).fill('Canteen               '),
          ...Array(5).fill('Gruel Kitchen         '),
          ...Array(5).fill('Labor Camp            '),
          ...Array(5).fill('Execution Chambers    '),
          ...Array(5).fill('Scrap Metal Workshop  '),
          'Slickscreen Classrooms',
          'Illegal Human Testing ',
          'Mind Wipe Lab         ',
          'Mass Grave            ',
          'Reprograming Facility ',
          'Military Black Site   ',
          'AI Prison Server      ',
          'Android Scrapyard     ',
          'Comissary             ',
          'Crematorium           ',
        ],

        religious: [
          ...Array(5).fill('Prayer Gardens'),
          ...Array(5).fill('Observatory'),
          ...Array(5).fill('Cellarium'),
          ...Array(5).fill('Chapter House'),
          ...Array(5).fill('Dorter'),
          ...Array(5).fill('Refectory'),
          ...Array(5).fill('Infirmiry'),
          ...Array(5).fill('Kitchens'),
          ...Array(5).fill('Lavatorium'),
          ...Array(5).fill('Misericord'),
          ...Array(5).fill('Scriptorium'),
          ...Array(5).fill('Calefactory'),
          ...Array(5).fill('Musalla'),
          ...Array(5).fill('Minaret'),
          ...Array(5).fill('Prayer Hall'),
          ...Array(5).fill('Ablution Fountains'),
          ...Array(5).fill('Chinjusha'),
          ...Array(5).fill('Three Gate'),
          'Bell Tower',
          'Shrine',
          'Lecture Hall',
          'Grand Reliquary',
          'Massive Statue',
          'Secret Chambers',
          'Palatial Gardens',
          'Scourging Room',
          'Bishop’s Manor',
          'Unmarked Prison Cell',
        ],

      rim_landmarks: [
        'Heavily Guarded Corporate DMZ  ',
        'Battered Asteroid Field        ',
        'Uninhabitable Desert Planet    ',
        'Strip-Mined Ice World          ',
        'First Generation Pioneer Colony',
        'Resource Rich Asteroid Cluster ',
        'The Disputed Territory Border  ',
        'Massive Jump-5 Derelict Hulk   ',
        'Burgeoning Off‑World Colony    ',
        'Ship Graveyard',
      ],

      rim_station: [
        'Independent Colony ',
        'Run Down Factory   ',
        'Military Base      ',
        'Lighthouse         ',
        'Asteroid Mining    ',
        'Maximum Sec. Prison',
        'Scrap Processing   ',
        'Rest & Refuel      ',
        'Black Market       ',
        'Abandoned Derelict ',
      ],

      call_sign: [
        'Remote Site-[d100]-[Letter]',
        '[d100]-[d10]',
        'Forward Base-[d10]-[Letter]',
        'Rimward-Post [d10]-[d10]',
        '[Letter]-[d100]',
        'Supervisor-[Letter]-[d10]',
        'Control-[d100]',
        'Command-[d10]-[d10]',
        'Outpost [d100]-[Letter]-[d10]',
        'Bridle-[d10]',
      ],

      control_faction: [
        'The Anders-Klimt Mining Corporation   ',
        'The Gaff Android Labor Syndicate      ',
        'The 601st Colonial Marine Regiment    ',
        'Salo-Mercury Biomotors Inc.           ',
        'The Apostles Gate Church              ',
        'Confederated Systems Inc.             ',
        'The “Opera” Fleet of Mercenary Raiders',
        'The Sindec Alloyed Metals Corporation ',
        'SEBACO Mining Ltd.                    ',
        'The Limited Colonial Government     ',
        'The Stratmeyer Syndicate',
      ],

      rival_faction: [
        'The Synthetic Liberation Front',
        'Altruistic Scientists         ',
        'Neo-Haram Anarchists          ',
        'Violent Return‑Earthers       ',
        'Carter Tactical Concerns Ltd. ',
        'Armadyne Weapons, Inc.        ',
        'House Sivaranjan              ',
        'Secret Union Instigators      ',
        'Black Dawn Mercenaries        ',
        'The Family of Eleven          ',
      ],

      rival_leader: [
        'Renegade Android',
        'Powerful Rogue AI',
        'Ruthless Criminal Despot',
        'Charismatic Revivalist',
        'Perverse Corp. Warden',
        'Highly Intelligent Merc. Captain',
        'Cunning Corporate Spy',
        'Merciless Slaver',
        'Stalwart Union Organizer',
        'Relentless Warrant Officer',
      ]
  };

export const CYBERNETIC_MUTATIONS = [
  'Teeth enlarged and coated in metal alloy.',
  ...Array(4).fill('Fingers lengthen. Fingernails turn into circuit boards. '),
  ...Array(5).fill('Eyes turn black. Wires spread from irises across face.  '),
  ...Array(5).fill('Voice loses its human quality. Now choral and robotic.  '),
  ...Array(5).fill('All hair falls out, tubing protrudes from back of skull.'),
  ...Array(5).fill('Vestigial synthetic appendage grows from ribcage.       '),
  ...Array(5).fill('Tangle of wires weave through your abdomen.             '),
  ...Array(5).fill('Metallic spinal column extrudes and pierces skin.       '),
  ...Array(5).fill('Limb consumed by mods. Misshapen metal mass.            '),
  ...Array(5).fill('Metallic fingers sprout from limb.                      '),
  ...Array(5).fill('Hand permanently fuses with equipped weapon.            '),
  ...Array(5).fill('Semi-organic vents form in underarms and neck.          '),
  ...Array(5).fill('Insectile eyes cluster across your face.                '),
  ...Array(5).fill('Tongue grows 6 times normal length. Constant drool.     '),
  ...Array(5).fill('Neck grows an extra foot and is sheathed in metal.      '),
  ...Array(4).fill('Heavy organic sac swells across your hunchback.         '),
  ...Array(2).fill('Neck vents grow and emit periodic exhaust fumes.        '),
  ...Array(2).fill('Half of face melts away revealing metal skull.          '),
  ...Array(2).fill('Spiked prongs extrude from your shoulders.              '),
  'Patch of 2d10 synthetic eyes grow out of your back.   ',
  'Arms grow until your hands touch the floor and drag.  ',
  'Metallic, wiry antlers grow from your skull.          ',
  'Second face grows out of your chest.                  ',
  'Mouths form in the palms of your hands.               ',
  'Hair turns to thick black wires, always seeking ports.',
  'Fingers fuse together and turn into metal claws       ',
  'Mouth splits into impossibly wide smile. Metal throat.',
  'Spines grow out of your arm bones.                    ',
  'Your skin becomes a liquid metal surface.             ',
  'Hoses grow from your torso and drag along the floor.  ',
  'The features of your face constantly drip and shift.  ',
  'Sensititve antennae grow from your skull.             ',
  'Your skin grows a tiny swarm of metal tentacles.      ',
  'Prefensile tail of wire and bone.                     ',
  'Entire body becomes shifting swarm of nanobots.       ',
  'Keyboard keys sprout from your arms.                  ',
  'A small person grows out of your torso.               ',
  'All your skin sloughs off to reveal a metal skeleton. ',
  'Roll twice and combine.                               ',
];

export const LOOT_POF = [
  'Credstick without ID. 1d100*100cr.',
  ...Array(4).fill('Credstick ID’d to vic. 1d100*10cr.'),
  ...Array(5).fill('VIP Invite to gamble in <b>Heaven</b>.'),
  ...Array(5).fill('Fake, rubber revolver. Looks pretty realistic.'),
  ...Array(5).fill('Functioning synthpet.'),
  ...Array(5).fill('Metallic folding fan.'),
  ...Array(5).fill('Leather jacket. “Суки Любят Острый Нож” (Bitches Love Sharp Knives) on back.'),
  ...Array(5).fill('Bundle of x5 Stimpacks and x4 Automeds.'),
  ...Array(5).fill('Empty O2 tank.'),
  ...Array(5).fill('Dried Meatapede.'),
  ...Array(5).fill('Bracelet with flashing colored lights.'),
  ...Array(5).fill('Flask of station hooch.'),
  ...Array(5).fill('Artisanal chocolate (relieves 2 Stress).'),
  ...Array(5).fill('<b>Patch</b>: “SUKA” (BITCH).'),
  ...Array(5).fill('Crossbow with 2d10 bolts.'),
  ...Array(4).fill('Intact Panzerfist cybermod.'),
  ...Array(2).fill('Map to a credit stash in <u>The Sink (pg. 34)</u>.'),
  ...Array(2).fill('SMG + 2 clips (non-frangible ammo).'),
  ...Array(2).fill('Adjudicator Guard’s modified Stun Baton. 3d10dmg.'),
  'Cryopack. Three human fingers. Fingerprints intact.',
  '<u>The Lottery Man</u> by Benno von Archimboldi.',
  'One shot mini flame thrower.',
  'CalixQ’s autograph on holopic. Worth 3d10*100cr.',
  'Dose of Sycorax.',
  'Well thumbed copy of <u>The Grasshopper Lies Heavy</u>.',
  '“Nemo” journal, recounting 4 days prior to a Sleeving.',
  'Pipebomb 5d10dmg, 4m radius.',
  'Subversive anti-corporate Samizdat literature.',
  'A small bottle of <u>Tendre Poison</u> eau de toilette.',
  'Dog-eared copy of the <u>Orange Catholic Bible</u>.',
  'O2 tank with 1d10 hours remaining.',
  'Inactive robotic spider named Icarus. Needs repair.',
  'Sheathed zipgun with 6 bullets.',
  '<u>La Boussole des précieux</u> (The Precious Compass), by Pierre Menard.',
  'A holomap of <u>Caliban’s Heart (pg. 38)</u>.',
  'Writhing cyberworm. Worth 1d10*1kcr.',
  'Tattooed piece of preserved skin.',
  'Raggedy broken doll. Still talks.',
  'Tempest Co. Exosuit. <b>Tagged</b>: “MAMA TRIED.”',
];

export const DERELICT = {
    ship_class:
    [
      ...Array(35).fill('Mining Frigate'),
      ...Array(23).fill('Freighter'),
      ...Array(14).fill('Shuttle'),
      ...Array(9).fill('Courier'),
      ...Array(4).fill('Research Vessel'),
      ...Array(4).fill('Blockade Runner'),
      ...Array(3).fill('Cutter'),
      ...Array(4).fill('Troopship'),
      ...Array(4).fill('Colony Ship')
    ],
    habitation_status: [
      ...Array(85).fill('Uninhabitable'),
      ...Array(10).fill('Habitable (non-functioning)'),
      ...Array(5).fill('Habitable (functioning)')
    ],
    survivors: [
      ...Array(90).fill('No survivors'),
      ...Array(6).fill('2d10 survivors (in cryosleep)'),
      ...Array(4).fill('Survivors')
    ],
    engine_status: [
      ...Array(81).fill('Engine, Thrusters, Jump Drive non-functioning'),
      ...Array(13).fill('Stable Engine, Thrusters, Jump Drive'),
      ...Array(6).fill('Unstable Core')
    ],
    salvage_1:  [
      ...Array(50).fill('2d100 units of scrap'),
      ...Array(26).fill('1d10 fuel unit(s)'),
      ...Array(6).fill('2d10 units of galley stock'),
      ...Array(4).fill('1d10 cryopods'),
      ...Array(3).fill('Medbay'),
      ...Array(3).fill('Weapon'),
      ...Array(4).fill('Computer'),
      ...Array(4).fill('Jump drive')
    ],
    salvage_2:  [
      ...Array(61).fill('4d10 units of ore'),
      ...Array(15).fill('3d10 units metal'),
      ...Array(10).fill('1d100 trade units of random cargo'),
      ...Array(7).fill('1d10 units of precious metal'),
      ...Array(7).fill('1d10 units of contraband')
    ],
    cause_of_ruination:   [
      'Virus',
      ...Array(9).fill('Combat'),
      ...Array(10).fill('Raided by Pirates'),
      ...Array(5).fill('Hyperspace Malfunction'),
      ...Array(5).fill('Abandoned Ship'),
      ...Array(5).fill('Insane AI                        '),
      ...Array(5).fill('Mutiny                           '),
      ...Array(5).fill('Crash: Other Ship                '),
      ...Array(5).fill('Crash: Space Debris              '),
      ...Array(5).fill('Crash: Jump Drive Miscalculation '),
      ...Array(3).fill('Engine Failure                   '),
      ...Array(3).fill('Cannibalism                      '),
      ...Array(3).fill('Nerve Gas                        '),
      ...Array(3).fill('Escape Pod Never Returned        '),
      ...Array(3).fill('Betrayal/Backstabbing            '),
      ...Array(2).fill('Succumbed to Nightmares          '),
      ...Array(2).fill('Hatch Opened, No Air             '),
      ...Array(2).fill('Cargo Created Mishap             '),
      ...Array(2).fill('Starvation                       '),
      ...Array(2).fill('Part of a Conspiracy             '),
      'Thrusters Slagged                ',
      'Weapons System Malfunction       ',
      'Cryosleep Never Disengaged       ',
      'Complex Series of Events         ',
      'Suicide Pact                     ',
      'Parasite Infestation             ',
      'Environmental Systems Failure    ',
      'Uncontrollable Fire              ',
      'Failed Fraud Attempt             ',
      'Void Worshipping                 ',
      'Bizarre Love Triangle            ',
      'Fight Spiraled Out of Control    ',
      'Chainsaw Rampage*                ',
      'Drug Addled Debauchery           ',
      'Fatal Depressurization           ',
      'Nightmares Ending in Heart Attack',
      'Mob Hit                          ',
      'Crew Members Vanished            ',
      'Prank Taken Too Far              ',
      'William Tell Trick               ',
    ],
    weird:   [
      'Haunted',
      ...Array(9).fill('Inhabited by Alien Life'),
      ...Array(10).fill('Terraformed by strange creatures'),
      ...Array(5).fill('Crew Dressed For Costume Party'),
      ...Array(5).fill('Crew All Identical'),
      ...Array(5).fill('Crew was preparing Theatrical Performance'),
      ...Array(5).fill('Morbid Artwork'),
      ...Array(5).fill('Pet Hoarders'),
      ...Array(5).fill('Erotic Sculptures'),
      ...Array(5).fill('Communist Regalia'),
      ...Array(3).fill('Company Uniform'),
      ...Array(3).fill('Cult Members'),
      ...Array(3).fill('Extensive Journals Kept'),
      ...Array(3).fill('Strange Health Obsession'),
      ...Array(3).fill('Unnervingly Clean'),
      ...Array(2).fill('Android was Poisoning Captain'),
      ...Array(2).fill('Ancient Ship'),
      ...Array(2).fill('Temporal Distortions'),
      ...Array(2).fill('Failed Utopia'),
      ...Array(2).fill('Crew Weighed and Measured Weekly'),
      'Extensive Body Modification',
      'Isolated Physics Anomalies',
      'Sexual Deviants',
      'Religious Extremists',
      'Transhumanist Android Worshippers',
      'Anti-Android Conspiracists',
      'Nauseating Stench',
      'Everything is Jury-Rigged',
      'Crew Taking Video Through the Catastrophe',
      'Body Horror',
      'Scooby-Doo Crew',
      'Interior Coated in Flesh, Doors are Membranes',
      'Whispering Echoes Always a Room Ahead',
      'Dolls in Macabre Tableaux',
      'Dead Crew: Exploded Heads',
      'Elaborately Posed Corpses (Hooks & Chains)',
      'Flickering Lights and Frenzied Screams',
      'Ship Rearranges Itself Frequently',
      'Ship Has Infinite Depth',
      'Fruit Basket, Greeting Card Inexplicably Addressed to Crew',
    ],
    cargo_type : [
      'Body Bags (Full)',
      'Wine',
      'Complex Navigational Equipment',
      'Ceramics',
      'Antique Books',
      'Garden Gnomes (Full of Illegal Stimulants)',
      'Opium',
      'Tea',
      'Silver Bars',
      'Sensitive Documents',
      'Anthropology Mission',
      'Botanists/Horticulturists',
      'Industrial Engineers/Architects',
      'Terraforming Equipment',
      'Hydroponic Plants',
      'Rare Wood',
      'Lab Rats',
      'Cultured Cells',
      'Cremains',
      'Drug Production Starter Equipment',
      'Common Cloth',
      'Designer Clothes',
      'Expensive Fish (Food)',
      'Pets',
      'Plastic Junk (gewgaws)',
      'Legionaries (guns & ammo)',
      'Religious Pilgrims (religious texts & symbols)',
      'Compressed Algae Blocks (1 = days rations, gross)',
      'Disarmed ordinance (lack detonators)',
      'Cars (high end)',
      'Medicine',
      'Cosmetics',
      'Race Horse Reproductive Material*',
      'Livestock',
      'Prisoners',
      'Mobile Black Site (used for completely illegal interrogations)',
      'Census Takers',
      'Cadmium',
      'Preserved Fruit',
      'Refugees'
    ]
};

export const HULL_SIZE = {
  'Blockade Runner': {
    die: 14,
    levels: 1
  },
  'Colony Ship': {
    die: 19,
    levels: 3
  },
  Courier: {
    die: 3,
    levels: 1
  },
  Cutter: {
    die: 9,
    levels: 2,
  },
  Freighter: {
    die: 16,
    levels: 2
  },
  'Mining Frigate': {
    die: 11,
    levels: 2
  },
  'Research Vessel': {
    die: 7,
    levels: 1
  },
  Shuttle: {
    die: 6,
    levels: 1
  },
  Troopship: {
    die: 14,
    levels: 2
  }
};

export const ROOM_INFO = {
  1: [
    '<b>LIFE SUPPORT</b>: Functional.',
    '<b>LIFE SUPPORT</b>: Repairable.',
    '<b>LIFE SUPPORT</b>: Non-repairable.',
    '<b>LIFE SUPPORT</b>: Radioactive (Body Save or 1d10 dmg).',
    '<b>COMPUTER</b>: Contains an intact map of the current sector.',
    '<b>COMPUTER</b>: Contains an intact map of a random sector.',
    ...Array(2).fill('<b>WEAPON</b>:')
  ],
  2: [
    '<b>JUMP DRIVE</b>: Intact and salveageable',
    '<b>JUMP DRIVE</b>: Completely smelted.',
    '<b>THRUSTERS</b>: Intact and salveageable.',
    ...Array(2).fill('<b>THRUSTERS</b>: Completely smelted.'),
    ...Array(2).fill('<b>ENGINE</b>: Intact and salveageable. 1d10 Fuel units.'),
    ...Array(2).fill('<b>ENGINE</b>: Completely destroyed and unuseable.'),
    '<b>ENGINE</b>: Rigged to explode in 1d10 minutes.'
  ],
  3: [
    ...Array(2).fill('<b>GALLEY</b>: 1d10 supply units remaining.'),
    '<b>GALLEY</b>: Completely barren, booby trapped.',
    '<b>GALLEY</b>: Roll on Weapon Cache table on page 13.',
    '<b>BARRACKS</b>: One survivor unconscious',
    '<b>BARRACKS</b>: Roll on Weapon Cache table on page 13.',
    '<b>BARRACKS</b>: Corpses.',
    '<b>LIVING QUARTERS</b>: Roll on Weapon Cache table on page 13.',
    '<b>LIVING QUARTERS</b>: Booby trapped.',
    '<b>LIVING QUARTERS</b>: Stowaway squatting here'
  ],
  4: [
    '<b>MEDBAY</b>: Stocked to the gills. Roll twice on Weapon Cache.',
    '<b>MEDBAY</b>: Completely picked over.',
    '<b>MEDBAY</b>: 3d10 Pain Pills, 2d10 Stimpaks',
    '<b>SCIENCE LAB</b>: Strange creature in containment.',
    '<b>SCIENCE LAB</b>: Quarantined. Body Save or 2d10 dmg.',
    '<b>CRYOCHAMBER</b>: Filled with corpses. Fear Save or 1 stress.',
    ...Array(2).fill('<b>CRYOCHAMBER</b>: 3d10 working cryopods'),
    '<b>CRYOCHAMBER</b>: 1d10 Cryopods that seem fine. 25% failure.',
    '<b>COMPLETELY DESTROYED ROOM</b>'
  ],
  5: [
    ...Array(7).fill('<b>CARGO HOLD</b>: Roll on Cargo table on page 9.'),
    '<b>CARGO HOLD</b>: Completely and totally empty.',
    ...Array(2).fill('<b>CARGO HOLD</b>: Currently being picked through by 2d10 armed scavengers. Roll on Cargo table on page 9.')
  ],
  6: [
    ...Array(4).fill('<b>CARGO HOLD</b>: Roll on Cargo table on page 9.'),
    ...Array(3).fill('<b>ENGINES</b>: 1d10/2 squatters in Vaccsuits huddling around the warmth of the engines.'),
    '<b>ENGINES</b>: Strange creature infestation.',
    ...Array(2).fill('<b>BARRACKS</b>: Fight between 2d10 scavengers and crewmembers of the ship’s original crew.')
  ],
  command: [
    '<b>COMMAND</b>: Single cockpit, scarred by gunfire.',
    '<b>COMMAND</b>: Bridge with working comm station.',
  ],
  thrusters: [
    '<b>THRUSTERS</b>: Intact and salveageable.',
    ...Array(2).fill('<b>THRUSTERS</b>: Completely smelted.'),
  ]
};

export const SHIP_WEAPONS = [
  'Laser Cannon',
  'Autocannon',
  'Railgun',
  'MG Turret',
  'Torpedoes',
  'Rigging Gun'
];

export const SHIP_NAMES = [
  [
    'IAGO',
    'HECATE',
    'OBERON',
    'WHITEHALL',
    'DUNCAN',
    'BANQUO',
    'WINTER',
    'MARLOW',
    'TEMPEST',
    'FAUST',
  ],
  [
    'VALEFOR',
    'OPHANIM',
    'MARAX',
    'MARINER',
    'LABOLAS',
    'ASTAROTH',
    'CHERUBIM',
    'TYRANT',
    'BALAAM',
    'MURMUR',
  ],
  [
    'ECHO',
    'ALPHA',
    'OMEGA',
    'KING',
    'BEGGER',
    'DELTA',
    'EPISLON',
    'JIBRIL',
    'BRAVO',
    'TANGO',
  ]
];

export const CACHE = [
  ...Array(15).fill('A ROTTING WOODEN BOX: ROSCO 556 NAIL GUN, 4 BOXES OF NAILS, MNC MODEL A LASER CUTTER, SPARE BATTERY, PEABODY FLARE GUN, 6 FLARES (HUNTER GREEN)'),
  ...Array(10).fill('A PICKED CLEAN ESCAPE POD: EVA MK-II HAND WELDER, HALLS B SERIES FOAM GUN, EMERGENCY BEACON, CROWBAR, INFRARED GOGGLES, FLASHLIGHT, STRAY BULLETS'),
  ...Array(3).fill('INSIDE A ROTTED TREE: A PRESERVED PRIMITIVE HUMANOID CORPSE CLUTCHES HARD METAL SPEAR (1D10 DAMAGE)'),
  ...Array(7).fill('A PAIR OF RUSTED FOOTLOCKERS: AUTOMED(X6), FIELD RECORDER, MEDSCANNER, HAZARD SUIT (4X), SCALPEL, MEDKIT, D&C 7 TRANQUILIZER PISTOL (2X)'),
  ...Array(5).fill('BLACK SYNTHETIC LEATHER SUITCASE: ELECTRONIC TOOLKIT, FLASHLIGHT, LOCKPICK SET, MRE (X7), PAIN PILLS (X18), FN “SLUG GUN” REVOLVER, SPEEDLOADER (X2), BOOK: IVY LEAGUE GUIDE TO BYPASSING SECURITY'),
  ...Array(10).fill('A TARP STITCHED SHUT: SURVEY KIT, VIBECHETE, WATER FILTER, RADIO JAMMER, REBREATHER, SK 109 SEEKER SMARTRIFLE, GHILLIE SUIT (WHEN UNMOVING: SEARCHING FOR YOU IS AN INTELLECT CHECK WITH DISADVANTAGE)'),
  ...Array(8).fill('LYING ATOP AN OCTAGONAL ALTAR, BEDECKED IN ORNATE BELLS: A PAIR OF CRUEL LOOKING ENERGY WHIPS (INTELLECT INSTEAD OF COMBAT, 2D10, 10% BREAK CHANCE)'),
  ...Array(10).fill('A WATER RESISTANT DUFFEL BAG: BINOCULARS, CAMPING GEAR, STIMPACK (X2), WATER FILTER, LOCATOR, REBREATHER, SK 109 SEEKER SMART RIFLE (2X), SPARE MAGAZINES (X8, JUNGLE CLIPPED), 4X EROTIC PICTORIAL MAGAZINES'),
  ...Array(2).fill('AN OILCLOTH WRAPPING CONTAINS: HAN-290 RIGGING GUN (X2), D&C 7 TRANQUILIZER GUN (X4), A GUIDE TO BIG GAME HUNTING (MANFUL CONQUEST)'),
  ...Array(10).fill('CANVAS “DOCTOR” BAG (CADUCEUS): BIOSCANNER, PAIN PILLS (X6), FIRST AID KIT, STIMPACK (X2), CYBERNETIC DIAGNOSTIC SCANNER, D&C 7 TRANQUILIZER PISTOL, ROSCO 556, BOOK: QUIETING THE SCREAMS: A PRIMER ON BEDSIDE MANNER'),
  ...Array(5).fill('A HUMANOID HUSK—TALL, WITH FOUR CLUSTERED EYES—WEARS ONLY A PAIR OF ORNATE BRACERS (1D10 DAMAGE, BLASTER OR EXTENDABLE BLADE; 10% BREAK CHANCE)'),
  ...Array(4).fill('BADLY CHARRED ASBESTOS FIRE SAFE: RAMHORN 1 FLAMETHROWER, FUEL TANK (X4), 1 GALLON KEROSENE, ZIPPO (ENGRAVED: “WHAT THE HAND, DARE SEIZE THE FIRE?”)'),
  ...Array(3).fill('A GEOMETRIC STACK OF UNKNOWN PURPOSE AROUND AN INTRICATELY WROUGHT METAL STAVE (2D10 DAMAGE BLAST OR 1D10 STRIKE)'),
  ...Array(5).fill('A HARDBODY GUITAR CASE: AZUREGLO RICKENBACKER 4001C64 ELECTRIC BASS IN CHERRY RED FINISH, ARMA 29 SUBMACHINE GUN, SPARE MAGAZINE (4X)'),
  ...Array(3).fill('RUSTED 10 FOOT SHIPPING CONTAINER (STENCILLED WITH PRIVATE MILITARY CONTRACTOR LOGO): KANO X9 COMBAT SHOTGUN (X4), ARMA 29 SUBMACHINE GUN (X4), F20 “ARBITER” PULSE RIFLE (X2) RAMHORN 1 FLAMETHROWER; BOXES: 200 SLUGS, 1 PULSE MAGAZINES, 20 ULTRA CAPACITY MAGAZINES, 4 FUEL TANKS'),
];

export const WARP_DRIVE = [
  ...Array(5).fill('A LARGE AQUARIUM IN THE MESS IS FILLED WITH:'),
  ...Array(5).fill('THREE BEFUDDLED SPACEFARERS LOUNGE ABOUT THE DECK, PERPLEXED THIS IS NOT THE GOLDEN HEART. THEY ARE: <b>RIO URIBE</b>, <b>CARA DELEVINGE</b> AND <b>IRINA LAZAREANU</b> (FASHIONABLE SOCIALITES). THEY WEAR CORSETED JACKETS, CRINOLINED BALLERINA SKIRTS AND TOWERING STILETTOS AND MAKE EXCELLENT NEGOTIATORS AND ALWAYS HAVE A CONTACT ANYWHERE THE CREW MAY WIND UP. THEIR SALARY IS 7,000 CREDITS AND THEY ONLY WORK AS A TEAM.'),
  ...Array(5).fill('PASS YOUR CHARACTER SHEET ONE SPACE CLOCKWISE; YOU ARE NOW THE CHARACTER PASSED TO YOU (IF APPLICABLE, AN NPC CONTROLLED BY THE DM IS PART OF THIS CIRCLE).'),
  ...Array(5).fill('WITHIN THE SHIP: GRAVITY IS DELAYED 3 SECONDS (OBJECTS REMAIN SUSPENDED FOR 3 SECONDS BEFORE FALLING) FOR 1d4 HOURS.'),
  ...Array(5).fill('TIME MOVES DIFFERENTLY FOR EVERYONE. TIME TO PHYSICALLY TRAVEL FOR EACH CREW MEMBER IS MEASURED IN (ROLLED INDIVIDUALLY): 1d4 SECONDS, MINUTES, HOURS, DAYS. LASTS 24 HOURS.'),
  ...Array(5).fill('IN THE POCKET OF EVERY CREW MEMBER IS A SEALED LETTER SIGNED BY A CREW MEMBER SELECTED AT RANDOM. THE LETTER IS AN ARDUOUS CONFESSION TO ACTS SO SINGULARLY VILE AND UNCONSCIONABLE THAT READING THEM TRIGGERS A STRESS TEST (D10/2). TO AID THE CREW MEMBER WHO “WROTE” EACH LETTER REQUIRES A FEAR SAVE.'),
  ...Array(5).fill('THERE IS AN ELABORATE LACQUERED BOX. INSIDE IS A BLACK CAT WITH WHITE EYES; ALL SCANS SHOW IT TO BE DEAD. IT IS PERFECTLY ALIVE AND SOMEWHAT FRIENDLY.'),
  ...Array(5).fill('A “BIRD”—THAT LOOKS LIKE A CUBIST PAINTING—FLUTTERS ABOUT, RECITING THE DIGITS TO PI. AT AN ARBITRARY POINT THE BIRD EXPLODES IN A SOFT HISS OF INK. THE NEXT MATHEMATICS CHECK EACH CREWMEMBER MAKES IS WITH ADVANTAGE.'),
  ...Array(5).fill('MOVEMENT IS BLINDINGLY FAST. YOU ACCELERATE AT BREAKNECK SPEED. YOU CAN VAPORIZE YOURSELF RUNNING INTO A WALL—BODY[-] SAVE TO NOT SMASH INTO A WALL FOR 4D10 DAMAGE. THIS ENDS IN WHAT FEELS LIKE SECONDS BUT IS ACTUALLY 4 HOURS.'),
  ...Array(5).fill('THE CREW ARE WHOLLY CONVINCED THEY ARE SOMEONE ELSE’S DREAM; THAT THEIR ENTIRE EXISTENCE IS SIMPLY FRAGMENTS OF A DREAMING STATE. THEY ARE IMMUNE TO STRESS CHECKS UNLESS SOMEONE SUGGESTS THE DREAMER MAY AWAKEN. IT ALSO REQUIRES A SANITY SAVE TO TAK RAPID SELF PRESERVING ACTION.'),
  ...Array(5).fill('PHYSICAL CONTINUITY IS OUT OF WHACK. WHEN THE CREW WALKS INTO A ROOM, INDIVIDUALLY ROLL FOR WHAT ROOM THEY WIND UP IN. THE ROOM’S ORIENTATION IS:'),
  ...Array(5).fill('EXITING WARP: THERE IS A TABLE SET WITH A FEAST AND A MARBLE BUST OF EACH CREW MEMBER ON THE TABLE FACING THEIR SEAT.'),
  ...Array(5).fill('EVERYONE BECOMES A MIRROR VERSION OF THEMSELVES (RIGHT HANDED PEOPLE BECOME LEFT HANDED, SCARS ARE ON OPPOSITE SIDE, ETC.). GAIN 2 STRESS. SOME GEAR MAY BE DIFFICULT TO USE.'),
  ...Array(5).fill('THE SHIP AND CREW HAVE BEEN BOUNCED BACKWARD BY A TIME RIPPLE.'),
  ...Array(5).fill('A DUPLICATE OF EVERY CREW MEMBER APPEARS. THE WARDEN ROLLS SECRETLY TO DETERMINE WHETHER EACH PLAYER IS THE ORIGINAL OR DUPLICATE.'),
  ...Array(5).fill('THERE’S A HEAVY MIST THROUGHOUT THE SHIP AND ALL SOUNDS ECHO FOR THE NEXT D10/2 HOURS.'),
  ...Array(5).fill('EVERYONE’S CLOTHING IS WORN THIN AND PATCHED UP AND IT WASN’T LIKE THAT BEFORE THEY ENTERED THE CRYOPODS.'),
  ...Array(5).fill('SHADOWS SEPARATE FROM THEIR OWNER, MOVING AHEAD OF THEM UNTIL A SANITY SAVE IS MADE.'),
  ...Array(5).fill('EVERY WOUND EVER RECEIVED REOPENS AND BLEEDS. PANIC CHECK. EVERYONE IS COVERED IN BLOOD UNTIL A SANITY SAVE IS MADE AND THE CREW REALIZES IT’S AN ILLUSION.'),
  ...Array(5).fill('EVERYONE THE CREWMEMBERS HAVE EVER LOVED AND LEFT BEHIND IS LOOKING AT THEM IN EVERY REFLECTION. THIS FADES GRADUALLY AFTER D10 DAYS. ROLL A DIE; EVEN RESULT: SANITY CHECK OR 1D10 STRESS EACH TIME THEY LOOK INTO A MIRROR, ODD RESULT: GAIN ADVANTAGE ON FEAR CHECKS FOR ONE DAY.'),
];

export const WARP_WEIRD = {
  fish: [
    'TILAPIA', 'TROUT', 'SALMON', 'JELLYFISH', 'CATFISH', 'OYSTERS', 'OCTOPI', 'SQUID', 'SNAILS', 'STRANGE MASS'
  ],
  time_ripple: [
    ...Array(4).fill('THEY EACH HAVE <b>5</b> MORE XP'),
    ...Array(2).fill('THEY CAN ROLL ADVANTAGE ON ALL SAVES THIS SESSION'),
    ...Array(2).fill('THEY CAN ROLL ADVANTAGE ON ALL CHECKS THIS SESSION.'),
    'THE SHIP HAS A NEW MODULE THAT WAS NEVER THERE BEFORE',
    'EVERYONE HAS d10 MORE STRESS.'
  ],
  room_orientation: [
    ...Array(5).fill('NORMAL'),
    ...Array(3).fill('INVERTED (LEFT-RIGHT)'),
    ...Array(2).fill('INVERTED (UPSIDE DOWN)')
  ]
};

export const VAULT = [
  'Neon Green Survival Hatchet',
  'Pepper Spray',
  'Throwing Knives',
  'A Jade Handled Sword Cane',
  'A Sawback Machete',
  'A Gunto Katana with paired Wakizashi',
  'A Pipe Bomb',
  'Barb Wire Wrapped Baseball Bat',
  'A Paired Set of Hot Pink ARMA 29 SMGs Bedecked with Diamonds',
  'A Papal Order of Planetary Excommunication',
  'A Glass Casket Containing A Bald, Stocky Man with a Tapered Beard and Trim Mustache in an Unremarkable Suit, a plaque reads Владимир Ленин (Vladimir Lenin)',
  'A Hollowed Out Holy Book containing Sacred Assassination Knives',
  'A Taxidermied Creature—Hybrid of a Snake, Rabbit and Parrot',
  'A Stack of Anti-Armor Mines',
  'A Stun Baton (Physical Attack, Unarmored Target Body Save or Collapse Unconscious)',
  'Semtex and a Detonator Cap',
  'A Set of Titanium Golf Clubs',
  'A Wildly Impractical and Ornate Claymore',
  'Full Coverage Chastity Cage',
  'Bondage Strap Corset (Halter/Choker)',
  'Book: Chastity Belts: An Illustrated History of the Bridling of Women',
  'Book: Voynich Manuscript',
  'Painting: A Maiden Holding A Chicken in a Field of Oranges',
  'Ming Vase full of Flaking Mannequin Arms',
  'A Silver Cigarette Lighter (Priapus)',
  'A Box Overflowing With Shurikens',
  'A Collapsible Compound Bow',
  'A Brick of Marijuana',
  'An Oil Drum of Personal Lubricant',
  'A Bronze Gladius',
  'A Mink Coat',
  'A Staggering Variety of Fireworks',
  'A Roman-Style Marble Statue of Pan Seducing a Goat (Covered With A Drop Cloth)',
  '60 Pain Pills in an Rx Bottle',
  'A Comically Ineffectual Knife (Festooned With Spikes and Curved Serrated Blades)',
  'A Carbon-Fiber Dao',
  'Bubinga Aklys',
  'A Brick of Cocaine',
  'Rhino-hide Litupa',
  'Book: Heptameron',
  'Extremely Gaudy Sissification Dresses',
  'Whalebone Corset',
  'Book: The Picatrix',
  'Book: Der Einzige und sein Eigentum',
  'Book: The Investiture of the Gods',
  'A Plastic Case of 12 Stimpacks',
  'A Bundle of Injectable Combat Drugs (all rolls related to violence are [+] for a day, cannot retreat from combat or fail a Fear check; afterwards Body Check[-] for addiction and go catatonic for 6 hours)',
  'A Pickled Mako Shark in a Formaldehyde Tank, Cut Into Arbitrary Sections for Display',
  'A Dress Made of Meat, Somehow Perpetually Fresh',
  'A Gigantic Marble Bust Making A Disapproving Face (a grown person can fit inside, the mouth acts as an amplifier)',
  'A Taxidermied Wooly Goat, its face Painted Strangely',
  'Elaborate Facial Harness with Ball Gag',
  'Vinyl Military Uniform',
  'Plastic Nunchucks',
  'Fully Articulated Pleasure Doll (Masculine, Rugged)',
  'Anime Body Pillow',
  'Brick of Heroin',
  'Unstable Hallucinogenic Research Chemical (Snortable)',
  'A Snake Shaped Staff (bites when striking, Body Save or Paralysis for 1d10 minutes)',
  'Book: No Title Just Byzantine Diagrams of Rope Bondage',
  'Ship-Breaching Charge (1d10 Hull Damage)',
  'Disturbing Restraint Chair with Fingernails Gouged in the Armrests',
  'A Functional (Well-Oiled) Iron Maiden',
  'A Sally Rod',
  'A Pitted and Rusted Set of Dental Tools',
  'A Leather Collar, “DADDY”',
  'Several Sheets of High Grade LSD',
  'Riot Shield (URBAN PACIFICATION UNIT)',
  'Book: Dominatrixes of Rog',
  'Book: Fundamentals of Brothel Management',
  'A Mace: the Beatific Face of Cupid',
  'A Set of Plastic Concealable Knives',
  'An Ebony Baphomet Statue',
  'A Box of Anti-Personnel Mines',
  'The Gilded Bones of a Saint in an Elaborate Reliquary Coffin',
  'A Talking Board',
  'A Magic 8-Ball',
  'A Case of Alertness Drugs',
  'Book: Dictators and Dictatorships: Understanding Authoritarian Regimes and Their Leaders',
  'Studded Leather Jacket, Patch: I REMAIN UNGOVERNABLE',
  'A Motorcycle',
  'A Pallet of Teargas Canisters and a Launcher',
  'A Rocket Propelled Grenade Launcher and 7 Shaped Core Rounds (1d10 dmg to buildings and ships; 1d100 damage to living targets)',
  'A Carton of Green Apple Cigarettes',
  'A Bottle of 18 Year Old Scotch',
  'A Case of Vodka',
  'Macuahuitl',
  'Religious Vestments, Robe and Meiter',
  'Gold-Plated, Bullet-Studded Gas Mask',
  'Flogger',
  'Riding Crop',
  'Zentai',
  'Babydoll Latex Mask',
  'A Box of Expensive Cigars with Cutter',
  'Tekko-kagi (Claws)',
  'Bronze Tintinnabulum',
  'Book: Le Veritable Dragon Rouge',
  'An Rx Bottle of 1d100 Anti Anxiety Pills ([+] on all Stress Checks for 8 Hours, Addictive)',
  'Painting: A Figure In Red Eats The Face of a Horse, Children Smile, The Sun is Black',
  'A Tea Service Made of Fur',
];

export const NIGHTMARES = [
  'Your migraine is splitting your skull. A dog rushes towards you, it’s eyes full of loving devotion. The dog’s head explodes into a crimson mist, coating your hands like an accusation.',
  'Your jaw unhinges as you vomit a torrent of earwigs.',
  'You are having sex with someone with the face of an ant; they regard you coldly and whisper something you can’t quite hear.',
  'You draw a straight razor across your mother’s eye. This is the right thing to do. She does not resist.',
  'There is the steady tick-tock of an egg timer in your chest. You know something terrible will happen when it rings. There is no clear way to stop it.',
  'An amber scorpion crawls on your face. Your limbs are leaden anchors a million miles away.',
  'You swim frantically, uncertain of which direction you are heading. The water is like ink, your lungs are bursting.',
  'You look at your hands. They fall apart like puzzle pieces. You cannot stop thinking about your 7th birthday.',
  'A crowd of beautiful, slim, fashionable and elegant people stare at you derisively. You drop your drink. They laugh with cruel, sensual smiles.',
  'Your ribs swell to make space for the blind orgy of wasp larva. You think about motherhood as your flesh stretches to its breaking point. The larva burrow out and unfold their iridescent wings.',
  'You are in a pale room. You hear the laughter of children. You cannot pinpoint the source.',
  'You feel the trapdoor spider making its home in your throat; you know what you have to do. Jamming the blade in is as simple as carving butter. You wiggle it around with satisfaction. You missed.',
  'A weathered hag sits on your chest, her mouth a hideous O of accusations. It won’t stop dripping pale fluids onto your face.',
  'You hear panicked screams in the darkness: they’re growing fainter, you are running away.',
  'Pale hands press against darkened glass. You are surrounded. Alone.',
  'No matter how much you struggle or bat them away, the crows are relentlessly consuming your face.',
  'You smell moss and dirt. Inane stammering and chanting fills your ears. They are coming for you.',
  'Figures flit about in the hanging fabric. You can’t quite make them out, they seem familiar. You aren’t certain if you are the hunter or the quarry.',
  'Your fingernails tear from their moorings as you futilely scrabble against the rough wall. The hole atop the shaft—your only escape— is as distant as the sky.',
  'Your eyes melt—crawling down your face like limpid tears. Your skin starts sloughing off. Your muscles fall off with a meaty slap. Maybe this face is not yours.',
  'You feel the slender fingers encircle your throat; there are too many of them, they are far too long and thin. Everything smells like camphor.',
  'A carousel spins madly—the music hellish, discordant. The horses’ eyes are meeting yours.',
  'You can smell the rot in your bones. You struggle to dig them out.',
  'Your face warps and shifts—stretching and pulling against its own definition. It becomes bovine. Your friends are leading you to a grey cement building. Everything smells like copper.',
  'Your fingers unwind like meaty corkscrews; they start anchoring you in place. The wind is cold.',
  'Your teeth blacken and rot. The crowd laughs uproariously. Nails drive through your putrid gums in a birth of pus and blood. You bite their faces away. They taste like cinnamon.',
  'A bulbous, fleshy, eyeless face hunts you in the dark. Its steps are deliberate. It has already found you.',
  'A puppet gazes up at you. A mockery of human features—exaggerated, stretched. Its hands spring into action, manipulating your strings. You dance a macabre waltz.',
  'A red sun slowly rises. The light carbonizes your toes, feet, legs. You watch. The smell of cooking meat overwhelms you.',
  'You fight a current of blind, swollen, pale fish to reach the masticating maw. There is a smell of jasmine.',
  'Your wrist bends back. It keeps bending. Your hand is in your arm.',
  'The shambling figure is dark, save a chipped porcelain mask. The air is hazy with the smell of candy and rot.',
  'Every door is labeled ‘EXIT’ despite taking you back to the start of the corridor. You have been here before.',
  'You pin the fish down. You bash its gasping face with a hammer. You can’t stop. You won’t stop.',
  'The music is pleasantly generic; the waiting room sterile. How long have you been here? How long will you remain?',
  'The skeletal cats need fed. They yowl, they fornicate, they piss. The air is thick with ammonia, wet with humidity. You lose count.',
  'You sip wine as she nails your fingers to the table. You have long, elegant hands.',
  'You stab the featureless body with a baby doll head, over and over. A torrent of red ants crawls from the womb.',
  'Your fingers are jagged snarls of glass. You caress yourself. You can’t feel how sticky your fingers are.',
  'The dinner party is lovely. Then you notice the centipedes crawling from your collar; hear the snide comments.',
  'The children dash ahead of you. Their rabbit masks are askew. You need to bring them home. You stumble.',
  'You feel them growing, behind your eyes. Your vision dims. You are the host and they are nothing like you.',
  'The pliers are getting red hot. The air is damp and unctuous. You don’t really need all those fingernails, not when you have so many toes.',
  'The ground is dry and desolate. Your drool pools by your face. You sink into the lukewarm puddle.',
  'It is cold. Your fingers blacken. You could snap them off if your hand would move. The cold scours everything away.',
  'You float in the void of deep space. A planet-sized foetus regards you with lugubrious, watery eyes.',
  'Poison gas fills the warrens. Blood seeps from their eyes as their despondent screams echo in your ears. Mocking laughter shakes your ribs like a bass note.',
  'He splatters his cravat with viscera when he cuts your hand off. You roll on the floor. You cauterize the stump with a hot plate. You line up your shot at the retreating figure. He spins around and shoots first.',
  'Your incisors won’t stop growing. They pry your jaw apart, your mouth wider and wider, lips bleeding from the strain, teeth grinding into gums. The snap will be a relief.',
  'You feel it churning inside you. Wrapping itself in your entrails. Kicking against your stomach wall. Waiting to break free, you can feel the grin fill the hollow of your belly.',
  'Filthy, louse-ridden children pelt you with stones. They know what you did.',
  'You bash the figure across the face with a rock. Your hands seek purchase on their face and you confidently press your thumbs into the eye sockets. Your own tortured face grins back.',
  'The sinuous reptiles circle you warily, languid motions at incredible speed. Their tongues taste the air, taste your body, your sweat tying them to you. Any second they will close in, their snapping jaws slathered with miasma.',
  'You crush the nimbus blue egg in your hand. Amidst the splintered shell fragments is the partially formed baby bird. It stares back at you with eyes like black marbles. Then you notice the teeth.',
  'Children with sunken eyes and rotted teeth chant, “SACRIFICE, SACRIFICE.” They push you, you fall. Their faces fade in the distance. You keep falling.',
  'You trudge through a landscape blanketed in bones. They snap and crunch underfoot. Drifts of them knee deep and pulling you gradually under. They rattle as you descend.',
  'You walk towards the horizon. You pass a burning car and the air is thick with malodorous smog. Your skeleton stops walking and is left behind. Your shadow tells you your real bones have been replaced.',
  'You are in a pool. The water is warm. Tropical fish peck away at you, each bite a papercut. You feel your legs gradually vanishing one small bite at a time. You can’t see an exit.',
  'You are lying on the beach, tangled in nets. The tide keeps rising up towards your face, gradually but inexorably. Gulls squabble and circle in the baking sun.',
  'Your face is smothered in kisses, teeth scraping your brow. A sudden rough bite and pull on the cheek till it tears leaving a hole. A tongue probes the fringes of the new orifice.',
  'You walk on broken glass, barefoot, the wet cracking of the shards your only companion save a floating red lantern illuminating the seemingly endless expanse of glass.',
  'The person talking to you is so unpleasant the world seems to curdle from the rancidness of their presence. Their hand is on your knee.',
  'A robot regards you. It mirrors your motions. It mimics your emotions. It takes your name.',
  'You feel sick, feverish, desperate. The bullet lodged in your gut is necrotizing too fast, spiderwebs of dying, blackened, leaking flesh.',
  'You are digging up a skeleton. The bones are impossibly fine, elegant even. The face long and gaunt, mournful. The wings so wide they consume the sky.',
  'The hammer feels momentous, pitted surface spattered with rust. You see the children with lambs’ faces. You silence their frenzied bleating.',
  'You bleed the pigs. All of them. In their fine jewelry and spotless dinner jackets.',
  'The bolt cutters pass through your joints roughly. The end announced by a smooth click. Your finger is discarded into the bucket. The bucket chews noisily.',
  'You claw at the glass. Your husk withering. They dispassionately take notes on clipboards. You dessicate and blow away in a fine spray of dust. They nod, approving.',
  'The Leviathan blots out the sun. The air ruptures as it breathes in. Its multifaceted eyes gaze upon you uncomprehendingly.',
  'Unnaturally white teeth grin at you, gleaming. The smile is forced. The laughter like a blade dragged across glass.',
  'The sky is an ink black horizon of tentacles and blazing vermillion eyes. It falls upon you like an avalanche. Tentacles force their way into your eyes, your mouth, down your throat. Your need is not slaked.',
  'Your hands are bound behind your back. The burlap over your head is tight, sucking in with your breath—the smell of kerosene overpowering. You feel wet, tired. You hear the scratch of a match being struck.',
  'You clip your nails. You keep clipping them. It won’t stop. You see bone.',
  'You’re at the end of the dock. Everything stinks of salt and rotting fish. Your feet squelch pointlessly in the concrete. They smoke cigarettes and leer at you. They’re coming over to push you.',
  'You follow the woman in the red damask dress through the hedge maze. She’s just out of reach. Her scent, peach blossoms, wafts behind her. You corner her. She turns around. There is no face, just a sunken pit with fleshy teeth.',
  'Scabrous rats—wounds dripping with pus—crawl all over you. Smother you with their wet, stinking bodies, force their way into your mouth and explore you. Where are your arms?',
  'You drive the nails into your leg. 1-2-3-4….99-100. Aghast, you realize your pattern isn’t symmetrical. You pry them out and start again—perfect this time.',
  'You see sharks circling in the wine dark sea. You are bleeding. It won’t stop.',
  'The ship controls won’t respond, all the systems are down. You are slowly drifting towards a sun. You perspire, your hands slipping as you struggle to stop the ponderous drift.',
  'You are beneath an immense pendulum. With each swing you feel years drain away. Your teeth disintegrate, your nails grow and twist, your vision dims, your hair becomes dust.',
  'Your arms are dragged in opposite directions as they are fed into gears. You feel the crushing weight and the tears forming in your muscles. Everything reeks of grease and rust.',
  'The airlock is slowly opening. Behind the glass they point and laugh. Your face is wet with tears. They enjoy slices of cake.',
  'You are engulfed in flame. No one seems to notice. Even when you touch them, spreading the flame. Vacant eyes.',
  'You’re bleeding from your mouth. Ropes of it suspended from your lips. The viscera starts moving of its own accord.',
  'You are crouched behind a crate. Pinned down by automatic arms fire. You can’t clear the jam.',
  'There’s a pulse grenade in your hands. You can’t remember how to throw, your fingers are useless. Everyone is disappointed.',
  'The mouth in your torso is hungry. It wants your friends. There are rewards for compliance.',
  'The conversation is charming, civil, courteous. The problem is they’re holding your hand in acid.',
  'A drill descends towards your eye. The whirr fills the air, gives it texture. They ask how you are feeling.',
  'No matter how many volts you deliver to the subject, he won’t divulge the information. He can’t last much longer, you hope. They are getting impatient.',
  'Your lips are being sewed shut. The needle dances in and out. There is something in your throat: you deserve this.',
  'You tear wrapping paper desperately from the gifts, shredded colorful paper piles up to your knees. The antidote is in one of these. It has to be.',
  'They deliver shocks to you. They ask you to prove you aren’t a machine. They don’t believe you.',
  'The snake is swallowing you. Everything smells of offal and carrion. It moves up your legs, relentless, devourer.',
  'Your fingers split and mutate into baby hands. The new hands repeat the process. The hands are getting heavy.',
  'Your arms become snakes. The snakes start biting you. You reach out towards your friends, share.',
  'The walls are closing in. Only when you close your eyes. Remain vigilant.',
  'You keep trying to scoop your guts back in; glistening ropes of your intestines wriggling and slipping in your hands. You’ve shoveled so much in. There should be an end to this.',
  'It is hot. It is dark. It is cramped. It is dusty. You are trapped.',
];

export const DEAD_SEARCH = [
  'Vial of amber liquid (alien-human hybrid foetus)',
  ...Array(9).fill('Breast Pocket Satanic Bible'),
  ...Array(9).fill('Key to a Storage Locker'),
  ...Array(5).fill('Scalpel'),
  ...Array(5).fill('Vitamin Sludge'),
  ...Array(5).fill('Lagomorph Foot'),
  ...Array(5).fill('Napkin (Coordinates Scribbled on Back)'),
  ...Array(5).fill('Lipstick'),
  ...Array(5).fill('2d10 Credits'),
  ...Array(3).fill('<i>"Touch the Void"</i> Cyanide Pills'),
  ...Array(3).fill('Music Player'),
  ...Array(3).fill('Bounty Notice for Relevant Crewmember'),
  ...Array(3).fill('Anxiety Medication'),
  ...Array(3).fill('Switchblade (Blade Says: <b>BAD BITCH</b>)'),
  ...Array(3).fill('Cheap Sunglasses'),
  ...Array(2).fill('Hula Girl'),
  ...Array(2).fill('Compass'),
  ...Array(2).fill('Spy Codebook'),
  ...Array(2).fill('Receipt for Alimony Payment'),
  ...Array(2).fill('<b>MOTIVATIONAL REMINDER:</b> <i>This Will Pass</i>'),
  '<b>BRACELET:</b> <i>Right Now, I Am Not In Danger. Right Now I Am Safe</i>',
  'Playing Cards (Marked)',
  '<b>BOOK:</b> <i>Horse Race Gambling Guide</i>',
  '<b>PIN:</b> <i>Panic!</i>',
  'Painkillers (Crushed to Snort)',
  'Postcard (Nice Casino)',
  '<b>COLONY SHIP BROCHURE:</b> <i>A New World For A New You',
  '<b>PIN:</b> <i>All Matter Wants To Be On Fire</i>',
  '<b>PAMPHLET:</b> <i>What A Union Can Do For You</i>',
  '<b>PIN:</b> <i>Bleed the Pigs</i>',
  'Animal Mask (Cloth)',
  'Box Cutter',
  '<b>BOOK:</b> <i>A Brief History of Hideous Dust</i>',
  'Thermal Lance (Tiny)',
  'Machete Saw',
  'Bandana',
  '<b>ZIPPO:</b> <i>FUCK CAPITALISM</i>',
  '.50Cal Round Bottle Opener'
];

export const MOON_COLONY = [
  ...Array(25).fill('Blindfold (Eyes Painted On)'),
  ...Array(5).fill('Glass Eye'),
  ...Array(5).fill('Venerated Goat Figurine'),
  ...Array(10).fill('Painkillers'),
  ...Array(5).fill('St. Christopher\'s Medallion'),
  ...Array(8).fill('Pack of Cigarettes (Green Apple)'),
  ...Array(6).fill('Tiny Wax Gaunt Sculpture'),
  ...Array(6).fill('Wrap Around Black Sunglasses'),
  ...Array(4).fill('<i>Grey\'s Anatomy</i> (Highlighting Focuses On Digestibility of Parts)'),
  ...Array(6).fill('"Never Sleep" Alertness Pills'),
  ...Array(3).fill('A Scalpel'),
  ...Array(3).fill('<b>PAMPHLET:</b> <i>A Great New Darkness</i>'),
  ...Array(3).fill('Anti-Anxiety Pills'),
  ...Array(3).fill('<b>PAMPHLET:</b> <i>Distilling Rocket Fuel Alcohol</i>'),
  ...Array(4).fill('Sculpting Tools'),
  ...Array(4).fill('Goat Visitation Token')
];

export const RED_TOWER = [
  ...Array(25).fill('Commando Knife with Compass'),
  ...Array(10).fill('3 Shotgun Shells'),
  ...Array(10).fill('SMG Magazine (Loaded)'),
  ...Array(10).fill('K Ration'),
  ...Array(6).fill('3 Potassium Flares'),
  ...Array(6).fill('Pack of Cigarettes (Red Apple Logo)'),
  ...Array(5).fill('Plastic Ziptie Handcuffs (4x)'),
  ...Array(4).fill('<b>PATCH:</b> <i>"TO DESTROY YOU IS NO LOSS"</i>'),
  ...Array(4).fill('<b>ZIPPO:</b> <i>FUCK OWLS</i>'),
  'Pinup Playing Cards',
  'Faded Photograph of a Child',
  'Music Box plays <i><a target="_blank" href="https://music.youtube.com/watch?v=nGGGQVGLTQ0&feature=share">"Tom Dooley"</a></i>',
  'Honorable Discharge Papers (Pension Eligible)',
  'Chopsticks',
  'Key (Storage Locker)',
  ...Array(2).fill('Packet of Dodgy "Alertness Powder" [Text Mosty Russian]'),
  'Sobriety Coin',
  'Canteen (Moonshine)',
  '<b>BOOK:</b> <i>Cook Crank With Your Mess Kit</i>',
  '<b>BOOK:</b> <i>Unions: A Parasite Draining YOUR Wages</i>',
  '<b>MAGAZINE:</b> <i>Thomas of Sweden</i>',
  '<b>PATCH:</b> <i>"I\'m Here To Defile Your Place of Worship"</i>',
  '<b>MAGAZINE:</b> <i>Hot to Frot</i>',
  ...Array(2).fill('<b>PATCH:</b> Grinning Reaper <i>"Let\'s Earn That Paycheck"</i>'),
  ...Array(2).fill('<b>PAMPHLET:</b> <i>The Faceless Hero: Grunts Through The Ages</i>'),
  'Shot Glass (Alien Bone)',
];

export const NECROPOLIS = {
  loot: [
    ...Array(21).fill('Nothing, Dust and Sorrow'),
    ...Array(10).fill('1d10 Uncut Gems'),
    ...Array(10).fill('1d100 Cerulian and Violet Shells'),
    ...Array(5).fill('Simple Spear(Hard Metal)'),
    ...Array(5).fill('Axe (Hard Metal)'),
    ...Array(8).fill('Tiny Metallic Floating Spheres which Dance Around Each Other.'),
    ...Array(7).fill('Intricately Wrought Metal Staff (Shoots Beams 2d10dmg, Strikes 1d10dmg, 10% Break Chance'),
    ...Array(3).fill('Small Palladium Figureines'),
    ...Array(4).fill('<b>BINDLE:</b> Revolver, 1d4 K Rations, Flare Gun, Trenching Shovel'),
    ...Array(3).fill('Gilded Skulls Set with Candles'),
    ...Array(5).fill('Painted Funerary Masks of Stone'),
    ...Array(5).fill('Patterned Steel Alloy Swords'),
    'A Silver Amphora',
    ...Array(3).fill('Thin Iridium Links'),
    'Black Metallic Jewelry with Luminscent Opals',
    ...Array(3).fill('Wax Gaunt Sculpture'),
    'Metallic Gaunt Sculpture',
    'Platinum Tear Drops',
    'Fired Clay Horror',
    'Brass Tablet with Ominous Pictograms',
    ...Array(2).fill('Surveyor\'s Notes')
  ],
  buildings: [
    ...Array(31).fill('Four-story Octagonal Complex'),
    ...Array(10).fill('Romansque Obelisk'),
    ...Array(5).fill('Brutal Monolith'),
    ...Array(5).fill('Tiered Circular Towers'),
    ...Array(15).fill('Incandescent Layered Dome'),
    ...Array(2).fill('Overgrown Park Featuring Grim Tile Mosaics'),
    ...Array(3).fill('Baraque Mausolea Covered in Bas-Reliefs'),
    ...Array(3).fill('Crumbled Arch'),
    ...Array(4).fill('Ornate Tower with Grotesque Statues'),
    ...Array(5).fill('Eroded Statue'),
    ...Array(2).fill('Mortuary Shrine'),
    ...Array(2).fill('Blood-Saturated Abattoir'),
    ...Array(4).fill('Ominous Crematorium'),
    ...Array(4).fill('Morbid Basilica')
  ],
  encounters: [
    ...Array(3).fill('Nothing'),
    ...Array(2).fill('Vociferous baying of <u>1d10 GAUNT HOUNDS</u> nearby (25% chance they track down PCs, unless precautions are taken).'),
    ...Array(2).fill('<u><b>6</b> GAUNT HOUNDS</u> vault from the rooftops, gently gliding down before falling among the crew, snapping and braying in a frenzy (SURPRISE on all but 1 in 10).'),
    '<u>1d10/2 GAUNT WALKERS</u>. Blood-curdling screech and reckless charge.',
    '<u>1d10 GAUNTS AND 1d6 GAUNT HOUNDS</u> ambush the PCs from all directions.',
    'The exquisite and dreadful figure of an <u>ALPHA GAUNT</u> ambles into view.'
  ]
};
